services:
  web:
    build: .
    container_name: news-system-web
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: news-system-db
    restart: always
    environment:
      MYSQL_DATABASE: news_system
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
